### ISSUE TITLE
Sitemap dependancy upon slickmap.css

### ISSUE THREAD

**Issue by zybiski** [Mokuji/mokuji#1]
As title. Sitemap is in base, depends on what seems to be a plugin. Dont have the plugin --> sitemap returns an error instead of displaying the page. 

exception\FileMissing
Could not load contents of C:/xampp/htdocs/plugins/SlickmapCSS/plugin.php. It is not a file.
Thrown in C:\xampp\htdocs\site\helpers\load.php on line 99.

**Comment by bartwr** [comment]
Thank you for this bug report. I just committed a fix, therefore the depedency is gone.
