### ISSUE TITLE
posting picture in CKEditor : elfinder doesnt work

### ISSUE THREAD

**Issue by zybiski** [Mokuji/mokuji#4]
Gives error : 
Invalid backend configuration.
Readable volumes not available.

cant upload images to text editor.

**Comment by bartwr** [comment]
Fixed in commit a5e20b4aa36a787801d94c84f7d0814ff82dc7f0. Beanow added the folder /files/explorer/ . Elfinder makes use of this folder and gave an error because the folder didn't exist yet.
