### ISSUE TITLE
exception/SQL

### ISSUE THREAD

**Issue by VDK** [Mokuji/mokuji#59]
When trying to load a page, sometimes I get this gibberish:

exception\Sql

Not unique table/alias: 'Layouts51cc83700c53b' in query: SELECT `Layouts51cc83700c53b`.\* FROM tx__cms_layouts AS `Layouts51cc83700c53b`, tx__cms_layouts AS `Layouts51cc83700c53b` WHERE 1 AND ((`Layouts51cc83700c53b`.`lft` >= `Layouts51cc83700c53b`.`lft`) AND (`Layouts51cc83700c53b`.`rgt` <= `Layouts51cc83700c53b`.`rgt`)) AND (`Layouts51cc83700c53b`.`id` IS NULL) GROUP BY `Layouts51cc83700c53b`.`id` ASC HAVING 1 ORDER BY `Layouts51cc83700c53b`.`lft` ASC

Thrown in C:\Program Files\EasyPHP-12.1\www\tx\site\system\core\Sql.php on line 98.

Callstack:

```
» core\Router::start()
  (index @ 42)
» core\Component::enter("'cms'")
  (Router @ 149)
» components\cms\EntryPoint::entrance()
  (Component @ 114)
» dependencies\Successable::success(object(Closure))
  (EntryPoint @ 331)
» components\cms\EntryPoint::components\cms\{closure}(object(dependencies\UserFunction))
  (Successable @ 76)
» dependencies\BaseComponent::view("'page'")
  (EntryPoint @ 322)
» dependencies\BaseViews::get_html("'page'", array())
  (BaseComponent @ 40)
» dependencies\BaseComponent::call("'page'", Data(NULL))
  (BaseViews @ 32)
» dependencies\BaseComponent::_call("'page'", array([0] => Data(NULL)))
  (BaseComponent @ 83)
» components\cms\Views::page(Data(NULL))
  (BaseComponent @ 128)
» dependencies\Table::execute()
  (Views @ 38)
» core\Sql::query("'SELECT `La...`lft` ASC '")
  (Table @ 652)
```

**Comment by VDK** [comment]
hitting F5 once or a couple of times does bring up the page :S

**Comment by Avaq** [comment]
Are you testing on a Windows server?

**Comment by VDK** [comment]
Yes
Op 1 jul. 2013 12:26 schreef "Aldwin Vlasblom" notifications@github.com
het volgende:
