### ISSUE TITLE
Is there any proper API documentation available?

### ISSUE THREAD

**Issue by VDK** [Mokuji/mokuji#61]
I saw this code for instance:  `$this->table('CbsNr')->pk($value->get())->execute_single();` for processing of a primary key, but how would you go about building a full SQL query?

**Comment by Avaq** [comment]
The extend of documentation we have for our Query Builder can be found [here](https://github.com/Tuxion/mokuji/blob/master/apidocs/dependencies/Table.md). It's not much, unfortunately, but we're working to improve documentation across the system.

**Comment by Avaq** [comment]
I'm working in a [separate branch](https://github.com/Tuxion/mokuji/tree/improved-docblocks) to improve documentation of big API's such as the query builder. Here you'll find that [Table.md](https://github.com/Tuxion/mokuji/blob/improved-docblocks/apidocs/dependencies/Table.md) is richer than the one linked in my previous post. As of yet, our doc block parser leaves quite a bit to be desired and in my opinion, the raw dock blocks in the [source file](https://github.com/Tuxion/mokuji/blob/improved-docblocks/site/system/dependencies/Table.php) are more clear. I will post another update on this issue once that has been improved.

**Comment by Beanow** [comment]
The mentioned documentation is now moved to the master repository.
See also an ORM guide: [/mokuji/docs/ORM.md](https://github.com/Tuxion/mokuji/blob/master/mokuji/docs/ORM.md)
And the generated API docs: [/mokuji/apidocs/API-index.md](https://github.com/Tuxion/mokuji/blob/master/mokuji/apidocs/API-index.md)
