### ISSUE TITLE
Choosing "Remember me" gives an SQL error on login

### ISSUE THREAD

**Issue by VDK** [Mokuji/mokuji#63]
Duplicate entry '1-0-0' for key 'PRIMARY' in query: INSERT INTO tx__core_user_persistent_authentication_tokens VALUES('1', 0, 0)

**Comment by bartwr** [comment]
Thank you for this bug report. I've seen the error in a few installations. Could be an update or core bug.

I'll come back on this later. In the meantime: don't check the 'Remember me' before logging in. Or empty the database table `#__core_user_persistent_authentication_tokens` to stay logged in.

:1234:

**Comment by Beanow** [comment]
This issue is resolved as of [Version 0.26.7 Beta](https://github.com/Tuxion/mokuji/releases/tag/0.26.7-beta).
The problem was with the random string generation code. The generator has been significantly improved now.
