### ISSUE TITLE
Error accessing backend

### ISSUE THREAD

**Issue by interlan** [Mokuji/mokuji#64]
After giving user name and password, error

Column 'date' cannot be null in query: INSERT INTO `mk__core_user_logins` VALUES( NULL, '1', '4j0467hqiffb1o9tbeqi04gnk3', NULL, '127.0.0.1', 'Mozilla/5.0 (Windows NT 5.1; rv:26.0) Gecko/20100101 Firefox/26.0', NULL )
Thrown in D:\uwamp\www\mokujicms\mokuji\system\core\Sql.php on line 93.

Win XP SP3, PHP 5.4.15, MySQL 5.6.11

Regards

Petros

**Comment by bartwr** [comment]
Hi Petros; First: great that you try out Mokuji!

It looks like the default value of the column `date` in the mk__core_user_logins database table isn't applied for some reason, in the system configuration you were using. The default value of the `date` column should be CURRENT_TIMESTAMP (http://2278766732.nl/upimg/2013q3/s-20131213-210530.png).

I don't see yet what causes the problem, but I'm sure we will find out. I will come back on this issue soon.

If you have any other questions, please let us know on GitHub Issues, or in the Mokuji forum: http://forum.mokuji.net . Thanks!

**Comment by Beanow** [comment]
@interlan Can you verify that your `date` column in the `mk__core_user_logins` table has `CURRENT_TIMESTAMP` as it's default value in your installation? If you use a tool like PHPMyAdmin, it should look like this: http://ss.oscp.info/ss_2013-12-19_12-04-22.png

**Comment by interlan** [comment]
I attach my PHPMyAdmin looks,
![1](https://f.cloud.github.com/assets/3278013/1782158/cae7c846-68a5-11e3-9059-d1d494e1e27f.jpg)

Cheers,
Petros (interlan)

**Comment by Beanow** [comment]
Sorry for the long long wait.

It seems that the value `NULL` was being inserted and the MySQL documentation prohibits this. Strangely enough inserting `NULL` works on every installation (Windows, OSX or Linux) we've tried so far.

The above update should fix this. To test it out, please download the `develop` branch and install that. Zip: https://github.com/Mokuji/mokuji/archive/develop.zip

**Comment by Beanow** [comment]
This fix is in Beta. https://github.com/Mokuji/mokuji/tree/release-0.31.0

**Comment by Beanow** [comment]
I'm assuming this fix has worked for you. Feel free to re-open it if you still have issues with this using the latest beta version.
