### ISSUE TITLE
Alternative login pages cannot preserve their PID throughout the password-reset process.

### ISSUE THREAD

**Issue by Beanow** [Mokuji/mokuji#66]
1. Create a new page that provides a login form.
2. Log out.
3. Open the new page and click the password reset option.
4. Send the request to your e-mail address (should have an account).
5. When the e-mail arrives, click the password reset link.
6. You will arrive at `/admin` or your `login_page` config value, instead of the new page.

This is a problem for websites with rich components providing their own log-in forms.
This process is supposed to be completed in a matter of minutes, users would get confused if they see a completely differently styled page.

Core problem: **user friendliness**

**Comment by Beanow** [comment]
Needs review using https://github.com/Tuxion/meta/blob/dev/dev/guides/patch-merging.md

**Comment by bartwr** [comment]
Works perfectly! Closed.
